### ISSUE TITLE
How did you do that snake eating your contribution thing

### ISSUE THREAD

**Issue by ankitkat042** [imaaquibali/awesome-github-profile#64]
I get that its a svg, but how you created it and where to upload it after creating it.

**Comment by imaaquibali** [comment]
> I get that its a svg, but how you created it and where to upload it after creating it.

<div  align="center"> <img src="https://raw.githubusercontent.com/muhiqsimui/ankitkat042/output/github-contribution-grid-snake.svg" /></div>
<img height="120" alt="Thanks for visiting my profile" width="100%" src="https://github.com/dibyendu415/dibyendu415/blob/master/marquee.svg" />

**Comment by imaaquibali** [comment]
@ankitkat042 did your problem solved?

**Comment by ankitkat042** [comment]
@imaaquibali no, i still couldn't figure it out how to custom move the snake to the contribution graph

**Comment by Lizz3108** [comment]
Hey, I have the same snake in my profile. For me this [article helped](https://ericagrundy.medium.com/how-to-add-a-snake-game-to-your-contribution-graph-on-github-e4b5fd295775)

**Comment by imaaquibali** [comment]
> Hey, I have the same snake in my profile. For me this [article helped](https://ericagrundy.medium.com/how-to-add-a-snake-game-to-your-contribution-graph-on-github-e4b5fd295775)

Thanks Lizze :)

**Comment by ankitkat042** [comment]
thanks @Lizz3108
